# Generated by Django 4.2.13 on 2024-06-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='data',
            new_name='date',
        ),
    ]
